language: node_js
node_js:
- stable
- '8'
cache:
  directories:
  - node_modules
script:
- npm run docs
- npm run test
deploy:
  provider: npm
  email: securisecdev@gmail.com
  api_key:
    secure: nTV8NqS6m9cVOMoa+79rTSj51p4KxJ35D3ImXletP2LuZ7DU+/66hFBHpdOkYlYfp37Q79SZE9+qyyBO7gVjJDI8z1U4fTsuN8/yNwNzqwH+y08j4C/leBAQ3i/TjWdOhMP/E8LgVl3QMrbltX4P1jdzeLQyCH8CARPp4H+NmNqgUtBXg6MYx92Evtz8Uq6XO5sO+G903wuHym/1BT1hTyGQKVzxVhZRMnnD3MHzvRaVnQxrSRw/efRRcP+jMzr5ucCivp7PnS5sO2yzLcqfz7TMqs3GGOWygUBj6gvT2df4C47lCZ7KRQ7TOb1pVKh0cZDKGCTklgRlzxlUuWxe+JmdFjYAGxSEh0EPVocYFgC2HbREqqzXckRDIOzsRWgtGIC4PxVdYDTrK6tI9qm88oI74xxxtMhW6hl6H+d+IGdIMhVWdmzm9w98lV/qNsgu64JczZ3ngyvqIGdhyE7aeGGrbQHsk04JtKonTmsgGJzhnFzUyMr5vMAegc4b+DUFcHY7hjZjjunxhO+kfmN+Nvc9ilF+B+IpePJebXWgwQ5VRnDVZtny+URFbsbHP5wKl9mJ52AzaN4qeyAQPw6HWXPy67TctA+lhAbJ/WUsOqF3toAutp8BHbe5PzaNfgne0yi51dHXXsFDn5Kpgl6HEi/H67Fay4BWTF2smuDU9pg=
  on:
    tags: true
    repo: securisec/condoit
